### PR TITLE
Fix names of EV3 UART sensors

### PR DESCRIPTION
**Pull request by in4lio**

### CODE REVIEW

**Comment by in4lio** [comment]
Sorry. I accidentally ruined the original pull request.

**Comment by dlech** [comment]
With regard to my comment https://github.com/ev3dev/ev3dev-kpkg/pull/1#issuecomment-76227233, what do you think about renaming the prefix from `lego-ev3-uart-` to `ev3-uart-type-`? My reason for wanting to do this is 1) Other sensor driver names are prefixed with the manufacturer, but in the case of EV3 UART sensors, all of the sensor information comes from the sensor itself. It does not send any manufacturer info but instead sends at "type id" to identify the sensor. This is why I am suggesting adding "type" to the prefix. Then the actual driver name will be `ev3-uart-type-%d` where %d is the type id.

**Comment by dlech** [comment]
By the way, I am planning on making some other breaking changes in the next kernel release, so this would be a good time to make this change.

**Comment by in4lio** [comment]
It seems very logical that you wrote about prefixes, in terms of beauty code. But in my opinion, the use of types numbers into the sensors names is not very comfortable for users. 'lego-ev3-uart-30' and 'ev3-uart-type-30' says ~~RTFM~~ nothing about what type of sensor it is. On other hand we can create user-friendly interface on the level of libraries...

In any case this commit just allows bring documentation into the actual state, also I need the correct 'sensors.json' file in ev3dev.github.io repo because it's a source for ev3dev-c code.

**Comment by dlech** [comment]
You have a good point. I have been reluctant to use user-friendly driver names in the case of UART sensors because the sensors send "everything you need to know" about the sensor. Since they only send a type id and not a real name, this is what I used. This way, any time a new sensor is released, I don't have to updated the driver.

But, I think you are right, it would be better to have a name that tells you what it is. So, I think in the next kernel release, I will add a lookup table to find a more friendly name. If a name is not found, then it will fall back to the type id.

And since you need the correct sensors.json, I'll go ahead and merge this and get the website updated.

**Comment by in4lio** [comment]
Super! Thank you.

**Pull request merged**
